---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[phabricator::default]
    attributes: {
        "phabricator": {
            "domain": "phabricator.example.com",
            "vcs_ssh": {
              "hosting_enabled": true
            }
        },
        "authorization": {
            "sudo": {
                "users": ["vagrant"],
               "passwordless": true
            }
        }
    }
  - name: arcanist
    run_list:
      - recipe[phabricator::arcanist]
    attributes:
